/Users/daniel/BA_SketchFix_Evaluation/Evaluation/venv/bin/python /Users/daniel/BA_SketchFix_Evaluation/Evaluation/SetupBug/replace_bug.py



#######################################################################################################
                             PROJECT: scrapy
#######################################################################################################
CLONING PROJECT:
✓ SUCCESSFUL! This project is already cloned: https://github.com/scrapy/scrapy
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/6/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/9/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/11/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/12/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/14/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/25/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/26/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/28/bug_patch.txt in the project scrapy does not exists. Next bug is taken
The file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/BugsInPy/projects/scrapy/bugs/38/bug_patch.txt in the project scrapy does not exists. Next bug is taken
.......................................................................................................
BUGGY LINES:
58,63
318,319
73
87

NF
54

NF
68,69
NF
NF
45
NF
47
13,50,62,65,70
51,52,54,55,57
62
140,149,162
35
104
147
29,55,24,30,38
81,95,96,98,104
NF
NF
58
NF
82
21,23,25,38,39
152,156,174
212,213
138,141,146,156,271
30
195,196
147,151,155
69
NF
69,71,74,75
276,277,278,279
.......................................................................................................

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 1

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spidermiddlewares/offsite.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spidermiddleware_offsite.py
GIT RESET TO: c57512fa669e6f6b1b766a7639206a380f0d10ce
HEAD is now at c57512fa Merge pull request #4384 from nyov/nodeb
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_exception_at_open_spider_in_pipeline (test_cmdline_crawl_with_pipeline.CmdlineCrawlPipelineTest) ... ok
test_open_spider_normally_in_pipeline (test_cmdline_crawl_with_pipeline.CmdlineCrawlPipelineTest) ... FAIL
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spidermiddlewares/offsite.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [58, 63]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 58
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_spidermiddleware_offsite (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 11, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 4, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_spidermiddleware_offsite (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spidermiddleware_offsite
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spidermiddleware_offsite.py", line 5, in <module>
    from scrapy.http import Response, Request
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 6, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
FAIL: test_open_spider_normally_in_pipeline (test_cmdline_crawl_with_pipeline.CmdlineCrawlPipelineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline_crawl_with_pipeline/__init__.py", line 17, in test_open_spider_normally_in_pipeline
    self.assertEqual(self._execute('normal'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 7 tests in 0.317s

FAILED (failures=1, errors=5)
✓
Start transforming line: 63
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 29 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:29
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 2

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/datatypes.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_datatypes.py
GIT RESET TO: f02c3d1dcf3e4880388d19e961e7911be5dc54ff
HEAD is now at f02c3d1d Use communicate() instead of wait() after killing the mock server (#4095)
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/datatypes.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [318, 319]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 318
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_datatypes (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_datatypes (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_datatypes
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_datatypes.py", line 10, in <module>
    from scrapy.utils.datatypes import CaselessDict, SequenceExclude
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
✓
Start transforming line: 319
x Fail! Line: 319 could not be transformed: 'self.popitem(last=False)'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 12 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[319]
✓ Number of created sketches:12
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 3

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py
GIT RESET TO: be2e910dd06ba4904e7b10eb5a7e3251e8dab099
HEAD is now at be2e910d Bump version: 1.7.0 → 1.8.0
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [73]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 73
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_redirect (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_redirect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_redirect
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py", line 5, in <module>
    from scrapy.downloadermiddlewares.redirect import RedirectMiddleware, MetaRefreshMiddleware
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
x Fail! Line: 73 could not be transformed: 'location = safe_url_string(response.headers['location'])'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[73]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 4

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/contracts/__init__.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_contracts.py
GIT RESET TO: c8f3d07e86dd41074971b5423fb932c2eda6db1e
HEAD is now at c8f3d07e Merge pull request #3367 from testingcan/doc-tutorial-update
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_contracts (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_contracts (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_contracts
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_contracts.py", line 3, in <module>
    from twisted.trial import unittest
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/contracts/__init__.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [87]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 87
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 5 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:5
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 5

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/response/__init__.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_response.py
GIT RESET TO: 426da0ed07637e7efbcfb0fe49546e187d5d7f67
HEAD is now at 426da0ed Merge pull request #3127 from Anjalizi/patch-2
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_http_response (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_http_response (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_http_response
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_response.py", line 5, in <module>
    from w3lib.encoding import resolve_encoding
ModuleNotFoundError: No module named 'w3lib'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 7

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/request/form.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_request.py
GIT RESET TO: e1ceaf3b5fa29326f032c4ed3f50943384b9e63d
HEAD is now at e1ceaf3b require w3lib 1.17+
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_http_request (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_http_request (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_http_request
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_request.py", line 12, in <module>
    from scrapy.http import Request, FormRequest, XmlRpcRequest, Headers, HtmlResponse
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/request/form.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [54]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 54
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:4
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 8

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/item.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_item.py
GIT RESET TO: f2f9350c47db73bdfb60773601b59b0633e1595a
HEAD is now at f2f9350c Merge pull request #2542 from scrapy/redirect-cleanup
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_item (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_item (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_item
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_item.py", line 3, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
x FAIL! Suspicious lines are empty!

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 10

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py
GIT RESET TO: 6cc83c041eac36e7688dbd9c4c55487a43b622e0
HEAD is now at 6cc83c04 Merge pull request #2330 from lfmattossch/note-python2-name
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_redirect (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_redirect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_redirect
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py", line 5, in <module>
    from scrapy.downloadermiddlewares.redirect import RedirectMiddleware, MetaRefreshMiddleware
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [68, 69]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 68
x Fail! Line: 68 could not be transformed: '   '
Start transforming line: 69
x Fail! Line: 69 could not be transformed: 'location = to_native_str(response.headers['location'].decode('latin1'))'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[68, 69]
✓ Number of created sketches:0
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 13

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/pipelines/images.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_pipeline_images.py
GIT RESET TO: fa78849e335994a1617ed63221a70940c21cca20
HEAD is now at fa78849e Merge pull request #2165 from loreguerra/master
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/pipelines/images.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [45]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 45
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_pipeline_images (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_pipeline_images (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_pipeline_images
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_pipeline_images.py", line 8, in <module>
    from twisted.trial import unittest
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:4
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 15

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/url.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_url.py
GIT RESET TO: b7925e42202d79d2ba9d00b6aded3a451c92fe81
HEAD is now at b7925e42 Merge pull request #2008 from foromer4/master
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/url.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [47]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 47
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR
test_utils_url (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_url (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_url
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_url.py", line 7, in <module>
    from scrapy.spiders import Spider
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
x Fail! Line: 47 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[47]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 16

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/url.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_url.py
GIT RESET TO: 73a5571c6044d5aea47b4f973e325c2f3d4e25dc
HEAD is now at 73a5571c Merge pull request #1923 from scrapy/request-new-safe_url_string
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/url.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [13, 50, 62, 65, 70]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 13
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR
test_utils_url (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_url (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_url
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_url.py", line 5, in <module>
    from scrapy.spiders import Spider
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
x Fail! Line: 13 could not be transformed: ''
Start transforming line: 50
x Fail! Line: 50 could not be transformed: '- remove fragments (unless keep_fragments is True)'
Start transforming line: 62
x Fail! Line: 62 could not be transformed: ''
Start transforming line: 65
x Fail! Line: 65 could not be transformed: '   '
Start transforming line: 70
x Fail! Line: 70 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[13, 50, 62, 65, 70]
✓ Number of created sketches:0
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 17

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/response.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_response.py
GIT RESET TO: ebef6d7c6dd8922210db8a4a44f48fe27ee0cd16
HEAD is now at ebef6d7c Merge pull request #1848 from aron-bordin/small_doc_style_fixes
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/response.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [51, 52, 54, 55, 57]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 51
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR
test_utils_response (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_response (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_response
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_response.py", line 5, in <module>
    from scrapy.http import Response, TextResponse, HtmlResponse
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
x Fail! Line: 51 could not be transformed: '>>> response_status_message(200)'
Start transforming line: 52
x Fail! Line: 52 could not be transformed: ''200 OK''
Start transforming line: 54
x Fail! Line: 54 could not be transformed: '>>> response_status_message(404)'
Start transforming line: 55
x Fail! Line: 55 could not be transformed: ''404 Not Found''
Start transforming line: 57
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[51, 52, 54, 55]
✓ Number of created sketches:4
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 18

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/responsetypes.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_responsetypes.py
GIT RESET TO: 41588397c04356f2b0c393b61ed68271a08d6ccd
HEAD is now at 41588397 Merge pull request #1765 from scrapy/add-deprecation-for-pydispatch
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_responsetypes (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_responsetypes (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_responsetypes
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_responsetypes.py", line 2, in <module>
    from scrapy.responsetypes import responsetypes
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/responsetypes.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [62]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 62
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 3 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:3
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 19

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/cookies.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_cookies.py
GIT RESET TO: e328a9b9dfa4fbc79c59ed4f45f757e998301c31
HEAD is now at e328a9b9 Merge pull request #1750 from scrapy/spider-is-idle
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_http_cookies (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_http_cookies (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_http_cookies
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_cookies.py", line 4, in <module>
    from scrapy.http import Request, Response
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/cookies.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [140, 149, 162]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 140
x Fail! Line: 140 could not be transformed: '   '
Start transforming line: 149
✓
Start transforming line: 162
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 11 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[140]
✓ Number of created sketches:11
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 20

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spiders/sitemap.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spider.py
GIT RESET TO: e328a9b9dfa4fbc79c59ed4f45f757e998301c31
HEAD is now at e328a9b9 Merge pull request #1750 from scrapy/spider-is-idle
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spider (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spider (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spider
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spider.py", line 6, in <module>
    from testfixtures import LogCapture
ModuleNotFoundError: No module named 'testfixtures'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spiders/sitemap.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [35]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 35
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 31 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:31
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 21

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/robotstxt.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_robotstxt.py
GIT RESET TO: 43a53aca1207a82b663fe7a90c375546ce340a8e
HEAD is now at 43a53aca Merge pull request #1746 from redapple/shell-settings-logging
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_robotstxt (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_robotstxt (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_robotstxt
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_robotstxt.py", line 3, in <module>
    from twisted.internet import reactor, error
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/robotstxt.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [104]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 104
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 3 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:3
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 22

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/exporters.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_exporters.py
GIT RESET TO: a35aec71e96b0c0288c370afa425e8e700dca8b3
HEAD is now at a35aec71 Merge pull request #1710 from redapple/1550-shell_file-cont
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_exporters (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_exporters (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_exporters
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_exporters.py", line 11, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/exporters.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [147]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 147
x Fail! Line: 147 could not be transformed: ''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[147]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 23

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/httpproxy.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_httpproxy.py
GIT RESET TO: c9e046d11dc63fbdc40effce4e6d15bcecd44593
HEAD is now at c9e046d1 Merge pull request #1657 from palego/os.mknod-fails-on-macos
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_httpproxy (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_httpproxy (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_httpproxy
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_httpproxy.py", line 3, in <module>
    from twisted.trial.unittest import TestCase, SkipTest
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/httpproxy.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [24, 29, 30, 38, 55]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 24
✓
Start transforming line: 29
✓
Start transforming line: 30
x Fail! Line: 30 could not be transformed: 'creds = base64.b64encode(user_pass).strip()'
Start transforming line: 38
✓
Start transforming line: 55
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 259 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[30]
✓ Number of created sketches:259
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 24

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/core/downloader/handlers/http11.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloader_handlers.py
GIT RESET TO: 98c060d0b2cc76934e16abc03a033f21850fd565
HEAD is now at 98c060d0 py3: fix http 1.1 test with https, and use self.host everywhere
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloader_handlers (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloader_handlers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloader_handlers
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloader_handlers.py", line 4, in <module>
    from twisted.trial import unittest
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/core/downloader/handlers/http11.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [81, 95, 96, 98, 104]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 81
x Fail! Line: 81 could not be transformed: '_responseMatcher = re.compile('HTTP/1\.. 200')'
Start transforming line: 95
x Fail! Line: 95 could not be transformed: 'tunnelReq = 'CONNECT %s%s HTTP/1.1\r\n' % (self._tunneledHost,'
Start transforming line: 96
x Fail! Line: 96 could not be transformed: '  self._tunneledPort)'
Start transforming line: 98
✓
Start transforming line: 104
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 4 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[81, 95, 96]
✓ Number of created sketches:4
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 27

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py
GIT RESET TO: 280eab241680c93a763a3ef3a9ccd0c257259ca0
HEAD is now at 280eab24 Merge pull request #1352 from nyov/le-bogus-links
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_redirect (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 13, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_redirect (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_redirect
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_redirect.py", line 3, in <module>
    from scrapy.downloadermiddlewares.redirect import RedirectMiddleware, MetaRefreshMiddleware
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/downloadermiddlewares/redirect.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [58]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 58
x Fail! Line: 58 could not be transformed: '   response.status in getattr(spider, 'handle_httpstatus_list', []))'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[58]
✓ Number of created sketches:0
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 29

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/request.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_request.py
GIT RESET TO: 5c4666a3d489bd3efa2e188de58721a125a5bfad
HEAD is now at 5c4666a3 Workaround for travis#253
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR
test_utils_request (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 13, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_utils_request (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_request
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_request.py", line 3, in <module>
    from scrapy.http import Request
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/request.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [82]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 82
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 30

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/cmdline.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_command_version.py
GIT RESET TO: 4d41cc0dc4821da07d467b368528c61ce48a0df2
HEAD is now at 4d41cc0d PY3 split requirements into files
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_command_version (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 5, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_command_version (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_command_version
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_command_version.py", line 1, in <module>
    from twisted.trial import unittest
ModuleNotFoundError: No module named 'twisted'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/cmdline.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [21, 23, 25, 38, 39]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 21
✓
Start transforming line: 23
x Fail! Line: 23 could not be transformed: '   issubclass(obj, ScrapyCommand) and \'
Start transforming line: 25
x Fail! Line: 25 could not be transformed: 'yield obj'
Start transforming line: 38
x Fail! Line: 38 could not be transformed: 'obj = entry_point.load()'
Start transforming line: 39
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 41 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[23, 25, 38]
✓ Number of created sketches:41
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 31

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/cookies.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_cookies.py
GIT RESET TO: 5f02ef82e8560242eb34b336f385addfdef3211d
HEAD is now at 5f02ef82 PY3 port http cookies handling
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_downloadermiddleware_cookies (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 5, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_downloadermiddleware_cookies (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_downloadermiddleware_cookies
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_downloadermiddleware_cookies.py", line 4, in <module>
    from scrapy.http import Response, Request
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/cookies.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [152, 156, 174]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 152
✓
Start transforming line: 156
x Fail! Line: 156 could not be transformed: '(to_native_str(k), [to_native_str(x) x in v])'
Start transforming line: 174
x Fail! Line: 174 could not be transformed: 'return [to_native_str(v) v in self.response.headers.getlist(name)]'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 2 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[156, 174]
✓ Number of created sketches:2
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 32

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/crawler.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_crawler.py
GIT RESET TO: 342cb622f1ea93268477da557099010bbd72529a
HEAD is now at 342cb622 DOC fix non-working link (by removing it).
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/crawler.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [212, 213]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 212
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_crawler (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 5, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_crawler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_crawler
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_crawler.py", line 4, in <module>
    from scrapy.crawler import Crawler, CrawlerRunner
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
✓
Start transforming line: 213
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 24 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:24
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 33

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
x FAIL! The bug test file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_pipeline_media.py;tests/test_utils_log.py to the project scrapy with bug: 33does not exists. Next bug is taken

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 34

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/item.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_item.py
GIT RESET TO: e521740b3951bacc80d3c9c1db8652ed5e914b89
HEAD is now at e521740b Merge pull request #1219 from Curita/fix-sphinx-warnings
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/item.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [30]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 30
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_item (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 5, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_item (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_item
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_item.py", line 3, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
x Fail! Line: 30 could not be transformed: 'fields = {}'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[30]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 35

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/crawler.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_crawler.py
GIT RESET TO: 0a5bbbaed3e182d2151b6b34357667901ece353f
HEAD is now at 0a5bbbae Merge pull request #1159 from scrapy/feed-export-fields
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_crawler (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 5, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_crawler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_crawler
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_crawler.py", line 4, in <module>
    from zope.interface.verify import DoesNotImplement
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import Settings, SettingsAttribute, CrawlerSettings
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/crawler.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [195, 196]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 195
x Fail! Line: 195 could not be transformed: 'cls_path = settings.get('SPIDER_LOADER_CLASS','
Start transforming line: 196
x Fail! Line: 196 could not be transformed: 'settings.get('SPIDER_MANAGER_CLASS'))'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[195, 196]
✓ Number of created sketches:0
Time needed: 0.01 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 36

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/misc.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py
GIT RESET TO: cb8140a42a27ede87b0880372024f2f1804618b8
HEAD is now at cb8140a4 Deprecate Response.body_as_unicode() (#4555)
TEST EXECUTION:
__init__ (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: __init__ (unittest.loader._FailedTest)
----------------------------------------------------------------------
TypeError: __init__() missing 2 required positional arguments: 'method_name' and 'exception'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/utils/misc.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [147, 151, 155]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 147
✓
Start transforming line: 151
x Fail! Line: 151 could not be transformed: ''
Start transforming line: 155
x Fail! Line: 155 could not be transformed: '"""Temporarily set environment variables inside the context manager and'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 2 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[151, 155]
✓ Number of created sketches:2
Time needed: 0.02 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 37

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/request/__init__.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_request.py
GIT RESET TO: 1d5c270ce8caf954ce83c8db262e2a35707e0c5e
HEAD is now at 1d5c270c Fix dangling file descriptor in FeedExporter when FEED_STORE_EMPTY is False (#4023)
TEST EXECUTION:
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/http/request/__init__.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [69]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 69
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_http_request (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_http_request (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_http_request
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_http_request.py", line 14, in <module>
    from scrapy.http import Request, FormRequest, XmlRpcRequest, JsonRequest, Headers, HtmlResponse
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 0 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[]
✓ Number of created sketches:0
Time needed: 0.0 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 39

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spiders/__init__.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spider.py
GIT RESET TO: 692975acb40c6394424dfb728b1ffa46b3b3c55d
HEAD is now at 692975ac deprecate Spider.make_requests_from_url. Fixes #1495.
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spider (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spider (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spider
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spider.py", line 6, in <module>
    from testfixtures import LogCapture
ModuleNotFoundError: No module named 'testfixtures'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 6, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/spiders/__init__.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [69, 71, 74, 75]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 69
✓
Start transforming line: 71
x Fail! Line: 71 could not be transformed: '"Spider.make_requests_from_url method is deprecated; "'
Start transforming line: 74
x Fail! Line: 74 could not be transformed: ')'
Start transforming line: 75
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 125 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[71, 74]
✓ Number of created sketches:125
Time needed: 0.03 minutes.

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+

                                          BUG: 40

+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+
bug_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/exporters.py
bug_test_file = /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_exporters.py
GIT RESET TO: 7d24df37380cd5a5b7394cd2534e240bd2eff0ca
HEAD is now at 7d24df37 Merge pull request #1681 from redapple/code-of-conduct
TEST EXECUTION:
test_cmdline (unittest.loader._FailedTest) ... ERROR
test_exporters (unittest.loader._FailedTest) ... ERROR
test_settings (unittest.loader._FailedTest) ... ERROR
test_spiderloader (unittest.loader._FailedTest) ... ERROR
test_utils_misc (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_cmdline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cmdline
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_cmdline/__init__.py", line 15, in <module>
    from scrapy.utils.test import get_testenv
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_exporters (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_exporters
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_exporters.py", line 10, in <module>
    import lxml.etree
ModuleNotFoundError: No module named 'lxml'


======================================================================
ERROR: test_settings (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_settings
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_settings/__init__.py", line 5, in <module>
    from scrapy.settings import (BaseSettings, Settings, SettingsAttribute,
ModuleNotFoundError: No module named 'scrapy'


======================================================================
ERROR: test_spiderloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_spiderloader
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_spiderloader/__init__.py", line 5, in <module>
    from zope.interface.verify import verifyObject
ModuleNotFoundError: No module named 'zope'


======================================================================
ERROR: test_utils_misc (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils_misc
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/tests/test_utils_misc/__init__.py", line 5, in <module>
    from scrapy.item import Item, Field
ModuleNotFoundError: No module named 'scrapy'


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
...........................
x TEST FAILS
✓ PyFix is started...

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

	                              PySketchFix®: Sketches are created.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PySketchFix will run with:
bug file: /Users/daniel/BA_SketchFix_Evaluation/Evaluation/Projects/scrapy/scrapy/exporters.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The suspicious lines which are taken are: [276, 277, 278, 279]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start transforming line: 276
✓
Start transforming line: 277
✓
Start transforming line: 278
x Fail! Line: 278 could not be transformed: ''
Start transforming line: 279
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Start creating 23 sketches.
✓
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
x Lines where no transformation is found:[278]
✓ Number of created sketches:23
Time needed: 0.03 minutes.
#######################################################################################################
Results with bug numbers:
Project:scrapy
Failing:[1, 2, 3, 4, 7, 10, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 27, 29, 30, 31, 32, 34, 35, 36, 37, 39, 40]
Empty Sus Lines: [5, 8]
Passing[]

Process finished with exit code 0
